server:
  port: 8080
spring:
  application:
    name: estatemanger
  main:
    banner-mode: off




  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    clean-disabled: true
    out-of-order: true
    locations:
      - classpath:db/migration
    table: flyway_schema_history
#logging:
#  level:
#    org:
#      springframework: DEBUG

#DataSource
datasource:
  url: jdbc:postgresql://localhost:5433/estate?createDatabaseIfNotExist=true
  username: postgres
  password: password
  driver-class-name: org
  hikari:
    max-connection-pool-size: 5
    min-idle-connections: 2

jwt:
  sign-secrets: dGhpc0lzQVZlcnlTZWN1cmVTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb25BbmRWYWxpZGF0aW9u


activation-code:
  ttl-in-minutes: 5
  base-url: http://localhost:8082/
  revoke-schedule-time: 6000